---
name: Adds all new issues to project board

on:
  issues:
    types: [opened]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up node16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Add new issue to classic project board
      uses: cb80/add2project@latest
      with:
        project: Validator issues
        column: To do
