name: Add new issue to project board

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add new issue to project board
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.1
        with:
          project-url: https://github.com/orgs/INSPIRE-MIF/projects/4
          github-token: ${{ secrets.PROJECT_AUTOMATION }}
