name: Adds all new issues to project board

on:
  issues:
    types:
      - opened

jobs:
  add-to-project-board:
    name: Add new issue to project board
    runs-on: ubuntu-latest
    steps:
      - name: Add new issues to project board
        uses: matmar10/add-issues-to-project@0.1.1
        with:
          gitub_token: ${{ secrets.PROJECT_AUTOMATION }}
          github_project_title: Validator issues
          github_org: INSPIRE-MIF

  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.1
        with:
          project-url: https://github.com/orgs/INSPIRE-MIF/projects/4
          github-token: ${{ secrets.PROJECT_AUTOMATION }}
